Repository MMC-Scholars/CrimeSolver, pull requests merged in 2021-01, with the labels that each got.

#10 Bugfix/polaroid capture black
  Content/Blueprints/Interactables/Items/Images/PolaroidInstant.uasset
Labels: bug

#12 Feature/sliding door
  Content/Blueprints/Interactables/DoorBP.uasset
  Content/Blueprints/Interactables/DoorPickupBP.uasset
  Content/Blueprints/Interactables/DrawerBP.uasset
  Content/Blueprints/Interactables/DrawerPickupBP.uasset
  Content/Blueprints/Interactables/SlidingDoorBP.uasset
  Content/Blueprints/Interactables/SlidingDoorPickupBP.uasset
  Content/Blueprints/Interactables/SlidingMeshBP.uasset
  Content/Maps/TestLevel.umap
Labels: enhancement

#13 Refactor/sliding door interaction
  Content/Blueprints/Interactables/SlidingDoorBP.uasset
  Content/Blueprints/Interactables/SlidingMeshBP.uasset
Labels: feature addition

#14 Feature/lightswitch
  Content/Blueprints/Interactables/LightSwitchBP.uasset
  Content/Maps/TestLevel.umap
  Content/Materials/lightswitch/Flip.uasset
  Content/Materials/lightswitch/Holder.uasset
  Content/Meshes/lightswitch_flip.uasset
  Content/Meshes/lightswitch_holder.uasset
Labels: feature addition

#15 Refactor/forensic light detection
  Content/Blueprints/Interactables/Items/Evidence/Evidence.uasset
  Content/Blueprints/Interactables/Items/Tools/ForensicLight.uasset
  Content/Blueprints/functions.uasset
  Content/Maps/TestLevel.umap
  Content/Materials/flashlight/Collection.uasset
  Content/Materials/flashlight/RevealTest.uasset
  Content/Materials/flashlight/SphereMask.uasset
  Content/Materials/flashlight/SphereMaskParams.uasset
Labels: bug, issue, refactor
