Repository MMC-Scholars/CrimeSolver, pull requests merged in 2021-02, with the labels that each got.

#17 Hotfix/fix polaroid scaling
  Content/Blueprints/Interactables/Items/Images/PolaroidInstant.uasset
  Content/Blueprints/Interactables/Items/Tools/Camera.uasset
Labels: bug

#16 Refactor/remove debugging
  Content/Blueprints/Boards/BIllboard.uasset
  Content/Blueprints/DesktopPawn/DesktopCharacterBP.uasset
  Content/Blueprints/DesktopPawn/Inventory.uasset
  Content/Blueprints/Interactables/Items/Images/Image.uasset
  Content/Blueprints/Interactables/Items/Tools/Camera.uasset
  Content/Blueprints/Interactables/Items/Tools/ForensicLight.uasset
  Content/Blueprints/functions.uasset
  Content/Maps/TestLevel.umap
Labels: refactor

#11 Feature/throw items
  Content/Blueprints/DesktopPawn/DesktopCharacterBP.uasset
  Content/Blueprints/DesktopPawn/Inventory.uasset
  Content/Maps/TestLevel.umap
Labels: feature
